require_relative '../config/environment.rb'


# user1 = User.create(Faker::Name.name)
# user2 = User.create(Faker::Name.name)
# user3 = User.create(Faker::Name.name)
# user4 = User.create(Faker::Name.name)
# user5 = User.create(Faker::Name.name)
Item.destroy_all 

vegetable1 = Item.create(item_name: "Broccoli", price: 2.99, category: "Vegetable")
# vegetable2 = Item.create("Peas", 1.99, "Vegetable")
# vegetable3 = Item.create("Zucchini", 1.99, "Vegetable")
# vegetable4 = Item.create("Green pepper", 2.99, "Vegetable")
# vegetable5 = Item.create("Onion", 0.99, "Vegetable")
# vegetable6 = Item.create("Spring Onion", 1.99, "Vegetable")
# vegetable7 = Item.create("Russet Potato",0.69, "Vegetable")
# vegetable8 = Item.create("Butternut Squash", 1.69, "Vegetable")
# vegetable9 = Item.create("Yukon Potato", 1.99, "Vegetable")
# vegetable10 = Item.create("White Mushrooms", 1.99, "Vegetable")
# vegetable11 = Item.create("Sweet Onion", 1.99, "Vegetable")
# vegetable12 = Item.create("Lettuce", 1.99, "Vegetable")
# vegetable13 = Item.create("Kale", 1.99, "Vegetable")
# vegetable14 = Item.create("Cucumbers", 3.99, "Vegetable")
# vegetable15 = Item.create("Collards", 1.99, "Vegetable")
# vegetable16 = Item.create("Sweet Potatoes", 2.99, "Vegetable")
# vegetable17 = Item.create("Eggplant", 1.99, "Vegetable")

fruit1 = Item.create(item_name: "Blueberries", price: 3.99, category: "Fruit")
# fruit2 = Item.create("Bananas", 0.50, "Fruit")
# fruit3 = Item.create("Strawberries", 4.99, "Fruit")
# fruit4 = Item.create("Grapes", 4.99, "Fruit")
# fruit5 = Item.create("Passionfruit", 6.99, "Fruit")
# fruit6 = Item.create("Apples", 1.99, "Fruit")
# fruit7 = Item.create("Cantaloupe", 1.99, "Fruit")
# fruit8 = Item.create("Watermelon", 5.99, "Fruit")
# fruit9 = Item.create("Blackberries", 2.99, "Fruit")
# fruit10 = Item.create("Raspberries", 2.99, "Fruit")

meat1 = Item.create(item_name: "Lamb", price: 4.99, category: "Meat")
# meat2 = Item.create("Chicken", 2.99, "Meat")
# meat3 = Item.create("Beef", 3.99, "Meat")
# meat4 = Item.create("Steak", 14.99, "Meat")
# meat5 = Item.create("Salmon", 9.99, "Meat")
# meat6 = Item.create("Pork", 3.99, "Meat")

dairy1 = Item.create(item_name: "Milk", price: 2.99, category: "Dairy")
# dairy2 = Item.create("Cheese", 2.99, "Dairy")
# dairy3 = Item.create("Butter", 3.99, "Dairy")
# dairy4 = Item.create("Heavy Cream", 2.99, "Dairy")
# dairy5 = Item.create("Yogurt", 0.99, "Dairy")

groceryitem1 = Item.create(item_name: "Rice", price: 0.99, category: "Grocery")
# groceryitem2 = Item.create("Flour", 0.69, "Grocery")
# groceryitem3 = Item.create("Crackers", 1.99, "Grocery")
# groceryitem4 = Item.create("Cereal", 2.99, "Grocery")
# groceryitem5 = Item.create("Oatmeal", 0.99, "Grocery")
# groceryitem6 = Item.create("Pasta", 1.99, "Grocery")
# groceryitem7 = Item.create("Quinoa", 3.99, "Grocery")
# groceryitem8 = Item.create("Toilet Paper", 10.99, "Grocery")
# groceryitem9 = Item.create("Juice", 4.99, "Grocery")
# groceryitem10 = Item.create("Soda", 3.99, "Grocery")


